### ISSUE TITLE
Still working? 

### ISSUE THREAD

**Issue by ViolentCrumble** [cathery/sys-ftpd-light#17]
Just wondering if this still works? How can I tell if it’s running? I can press the key combo and the home button light flashes either twice or once. But I can’t connect no matter what I do. I have set both the username and password and triple checked the config file.

I even installed the ovl overlay but the ip shows black. 

I installed another FTP and it works straight away. However would prefer to use this app as it runs in the background and I can copy files even when doing something else. 

Please let me know if there is any way I can get an error or debug this.

**Comment by ms2048** [comment]
v1.0.4 works for me on Atmosphere 0.19.3 and emunand 12.0.2 (modded Marko unit booted via SX Gear and Hekate 5.5.6). It is considerably slower than ftpd pro for some reason (I mean file transfers in both directions). Still, the convenience of having it in the background is huge, so I have both configured on different ports.

Strange thing: ftp itself works ok but I cannot get the home button to flash at all (neither on connection nor on key combo - which otherwise also works), despite having led:=1 set in config.

sys-ftpd-ovl shows the ip address correctly, so maybe there is some problem on your side?

**Comment by ViolentCrumble** [comment]
yeah definitely an issue on my side, I was asking how can i debug to find out what the issue is? I believe my switch runs v11 fw. I use atmosphere unsure which version. Also running emunand.

**Comment by ms2048** [comment]
I'm no expert but I'd suggest concentrating on sys-ftpd-ovl getting an IP first - it should just work. It is very simple [piece of code](https://github.com/SegFault42/sys-ftpd-ovl/blob/3d3a4687c26cd1a998bdb5bd7f0e95ec88a08c73/source/main.cpp#L36), independent of sys-ftpd-light, so debugging it should be easier.

Also, maybe try clean/upgraded environment with versions mentioned (on a separate card)?

**Comment by ViolentCrumble** [comment]
thank you. I did not realise i could just make a whole another environment using another sd card. lol that is handy.

Well my switch was only done a few weeks back. The firmware was 11.0 and i used the latest of everything then. So I can't say the versions off the top of my head but can check when i get home. But i assume pretty recent.

**Comment by ViolentCrumble** [comment]
also sorry i should mention. I know the IP of my switch. I can use the FTP pro app just fine. It shows the same IP i expect. Also i believe the Ftpd-light is running since the home button lights up when I press the key combo.

**Comment by ms2048** [comment]
I suppose you know the IP but I have been referring to you saying 'the ip shows black' about the overlay. On my switch, the IP is displayed correctly there (even without sys-ftpd-light installed at all), so there you have it: a simple piece of code that does not work - but should work, so if I were you, I would start debugging here.

That's what I meant before, sorry if I have been ambiguous.

Also beware: the difference between HOS 11.x and 12.x is big enough for at least some homebrew apps to stop working. Fortunately, sys-ftpd-light isn't one of them.

**Comment by ViolentCrumble** [comment]
oh yeah totally got what you meant. not ambiguous at all! Just was thinking even if the overlay is wrong the app is running. But i just realised that the overlay prob is not showing the ip of the switch but instead showing the IP of the ftp server? if that is right then it is probably due to the ftp server not actually running lol. 

I will try resinstalling tonight.

**Comment by ms2048** [comment]
Like I said previously - on my switch, the overlay (sys-ftpd-ovl) works correctly (shows IP address of the switch) even without the server (sys-ftpd-light) installed.

**Comment by ViolentCrumble** [comment]
So it turns out I am an idiot and placed the config file in atmosphere/config instead of the config file in the root directory. 

Closing this haha
