### ISSUE TITLE
[Feature Request] pause/unpause notification LED

### ISSUE THREAD

**Issue by Localhorst86** [cathery/sys-ftpd-light#4]
I understand that removing sound notifications was most likely necessary in order to reduce the memory footprint of the module. These were, however, very useful when enabling or disabling the ftp server. I think this could sensibly be replaced with a flash of the home button, have the button flash once when enabling the ftp server and twice when disabling it. Preferably, this could be configurable and it should be independent from the "connection" LED.

I.e. it would probably be a good idea to have the LED only light up when enabling or disabling the ftp if one wishes so.

**Comment by cathery** [comment]
Your description is very confusing, but i think you're talking about pausing the FTP server with the key combination? In which case it's a good point, because there's no more indication whether you've paused it or not

**Comment by Localhorst86** [comment]
Yes, I was talking about pausing/unpausing the ftp server with the key combo :)
As of now, there is no indication if it is paused or unpaused.

**Comment by cathery** [comment]
It will now flash an LED notification when pausing and unpausing. When you pause, there will be a "double click", and when you unpause, there will be a single long "resume". I hope it makes sense.
