### ISSUE TITLE
List failed for folders have large amount file/sub folders

### ISSUE THREAD

**Issue by 424778940z** [cathery/sys-ftpd-light#6]
Here is the FileZilla log

CMD:	CWD /_ns_game_nsp
RES:	200 OK
CMD:	PASV
RES:	227 192,168,42,229,143,225
CMD:	MLSD
RES:	150 Ready
RES:	550 unavailable
ERR:	listing failed

**Comment by cathery** [comment]
I have a folder full of 2048 files and a folder full of 2048 folders. All of them are being read just fine from FileZilla. So unless you're more descriptive about your error, I can't reproduce it.
