### ISSUE TITLE
LED on Pro Controller home button stays on after disconnecting from server

### ISSUE THREAD

**Issue by vezelas** [cathery/sys-ftpd-light#9]
After disconnecting from the server the notification light on the joycons turn off, but the light on the switch pro controller stays on unless I hit the power button on the console or the reset/sync button on the pro controller.

**Comment by cathery** [comment]
Is all of your controllers' firmware up to date? If not, does the issue still occur after you've updated the firmware?

**Comment by vezelas** [comment]
All of my controllers are up to date.

**Comment by cathery** [comment]
I'm looking at the code now, it lights up the LED for up to 5 controllers, but disconnects only the first. Makes no sense to me that it tries to light up multiple LEDs; would you be okay if I made it light up only the first controller?

**Comment by vezelas** [comment]
Sounds good!

**Comment by cathery** [comment]
It will now only flash LED for the handheld joycons if no other controllers are connected, or the first player controllers if they are found. Additionally this also fixes all the LEDs that would stay on in controllers with old firmware.
